name: sticky_hierarchical_scroll_example
description: Demo app for sticky_hierarchical_scroll
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  sticky_hierarchical_scroll:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
